<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="django.contrib.auth.tests.views.LogoutTest" tests="7" time="0.006">
	<testcase classname="django.contrib.auth.tests.views.LogoutTest" name="test_14377" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.LogoutTest" name="test_logout_default" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.LogoutTest" name="test_logout_with_custom_redirect_argument" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.LogoutTest" name="test_logout_with_next_page_specified" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.LogoutTest" name="test_logout_with_overridden_redirect_url" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.LogoutTest" name="test_logout_with_redirect_argument" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.LogoutTest" name="test_security_check" time="0.001"/>
	<system-out/>
	<system-err/>
</testsuite>
