<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="django.contrib.auth.tests.management.GetDefaultUsernameTestCase" tests="3" time="0.002">
	<testcase classname="django.contrib.auth.tests.management.GetDefaultUsernameTestCase" name="test_existing" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.management.GetDefaultUsernameTestCase" name="test_i18n" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.management.GetDefaultUsernameTestCase" name="test_simple" time="0.001"/>
	<system-out/>
	<system-err/>
</testsuite>
