<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="django.contrib.auth.tests.auth_backends.RowlevelBackendTest" tests="3" time="0.002">
	<testcase classname="django.contrib.auth.tests.auth_backends.RowlevelBackendTest" name="test_get_all_permissions" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.auth_backends.RowlevelBackendTest" name="test_get_group_permissions" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.auth_backends.RowlevelBackendTest" name="test_has_perm" time="0.001"/>
	<system-out/>
	<system-err/>
</testsuite>
