<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="django.contrib.auth.tests.forms.PasswordResetFormTest" tests="5" time="0.004">
	<testcase classname="django.contrib.auth.tests.forms.PasswordResetFormTest" name="test_bug_5605" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.forms.PasswordResetFormTest" name="test_cleaned_data" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.forms.PasswordResetFormTest" name="test_inactive_user" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.forms.PasswordResetFormTest" name="test_invalid_email" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.forms.PasswordResetFormTest" name="test_nonexistant_email" time="0.001"/>
	<system-out/>
	<system-err/>
</testsuite>
