<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="django.contrib.auth.tests.decorators.LoginRequiredTestCase" tests="4" time="0.003">
	<testcase classname="django.contrib.auth.tests.decorators.LoginRequiredTestCase" name="testCallable" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.decorators.LoginRequiredTestCase" name="testLoginRequired" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.decorators.LoginRequiredTestCase" name="testLoginRequiredNextUrl" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.decorators.LoginRequiredTestCase" name="testView" time="0.001"/>
	<system-out/>
	<system-err/>
</testsuite>
