<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="django.contrib.auth.tests.basic.BasicTestCase" tests="4" time="0.003">
	<testcase classname="django.contrib.auth.tests.basic.BasicTestCase" name="test_anonymous_user" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.basic.BasicTestCase" name="test_createsuperuser_management_command" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.basic.BasicTestCase" name="test_superuser" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.basic.BasicTestCase" name="test_user" time="0.001"/>
	<system-out/>
	<system-err/>
</testsuite>
